[package]
name = "simple_attr"
version = "0.1.0"
authors = ["shota.f <shota.fk8@gmail.com>"]
edition = "2018"

[lib]
proc_macro = true

[dependencies]
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
